#### Working with vectors in NumPy

##### Creating Vectors and Extracting Values

In [2]:
#Basic creation with np.array
import numpy as np
list_of_num = [4, 8, 15, 16, 23, 42]
array = np.array(list_of_num)
print(type(array))
print(array)

<class 'numpy.ndarray'>
[ 4  8 15 16 23 42]


In [4]:
#Extract value 
first_element = array[0]
print(first_element)
last_element = array[-1]
print(last_element)

4
42


In [5]:
#Setting values
array[0] = 100
print(array)

[100   8  15  16  23  42]


In [6]:
array[-1] = 1000
print(array)

[ 100    8   15   16   23 1000]


In [10]:
#Creating vectors with np.arange
sequential_number = np.arange(17,23, 2.5)
print(sequential_number)

[17.  19.5 22. ]


In [11]:
# Import the NumPy package with alias np
# Use np.arange to create a vector with six elements ranging from 3 to 8.
vector = np.arange(3,8)
print(vector)

[3 4 5 6 7]


In [13]:
# Importing the numpy package with the alias np
import numpy as np

# Defining the vector called my_vector
my_vector = np.array([1, 4, 5, 10, 13, 9, 10])

# YOURE CODE GOES BELOW HERE!
# Change the last value to 100
my_vector[-1] = 100
print(my_vector)

[  1   4   5  10  13   9 100]


#### Basic Operations

In [18]:
first = np.arange(1,5) # 1 2 3 4
second = np.array([6,8,3,2])

#Addition 
summation = first + second
print(f'sum: {summation}')

#Subtraction
subtraction = first - second
print(f'sub: {subtraction}')

#Multiplication
multiply = first * second
print(f'multiply: {multiply}')

##Division
division = np.around(first / second, 3)
print(f'division: {division}')

#Expomentation
expomentation = first ** second
print(f'expomentation: {expomentation}')

sum: [ 7 10  6  6]
sub: [-5 -6  0  2]
multiply: [ 6 16  9  8]
division: [0.167 0.25  1.    2.   ]
expomentation: [  1 256  27  16]


In [21]:
# Importing the numpy package with the alias np
import numpy as np

# Defining the vectors called first_vector and second_vector
first_vector = np.array([1, 4, 0, 10, 13, 9, 10])
second_vector = np.array([8, 4, 9, -1, 1, 19, 99])

# YOURE CODE GOES BELOW HERE!
# sum of first_vector and second_vector
sum_of_vectors = first_vector + second_vector
print(f'sum: {sum_of_vectors}')

# first_vector divided by second_vector
first_divided_by_second = np.around(first_vector / second_vector, 2)
print(f'divide: {first_divided_by_second}')

# three multiplied by the square of the first_vector
three_first_square = (first_vector ** 2) * 3
print(f'multiply: {three_first_square}')

sum: [  9   8   9   9  14  28 109]
divide: [  0.12   1.     0.   -10.    13.     0.47   0.1 ]
multiply: [  3  48   0 300 507 243 300]


#### NumPy DataTypes

In [25]:
#What datatypes does NumPy have?
array = np.array([4, 8, 15, 16, 23, 42])
print(array.dtype)
array.dtype

int32


dtype('int32')

In [27]:
#What datatypes does NumPy have?
array = np.array(np.int64([4, 8, 15, 16, 23, 42]))
print(array.dtype)
array.dtype

int64


dtype('int64')

In [28]:
#What datatypes does NumPy have?
array = np.array([4.5, 8.2, 15.55, 16, 23, 42])
print(array.dtype)
array.dtype

float64


dtype('float64')

In [35]:
#We can specify the datatype
array = np.array([4, 8, 15, 16, 23, 42], dtype=np.int32)
print(array.dtype)
#int8 can store up to 127
array = array + 100
print(array)

int32
[104 108 115 116 123 142]


In [36]:
#Size of a vector
print(len(array))
print(array.size)

#Number of bytes
print(array.nbytes)

6
6
24


#### Slicing

In [37]:
array = np.array([4, 8, 15, 16,23, 42])

In [42]:
#Everything after an index
print(array[0:])
print(array[1:])
print(array[2:])
print(array[3:])

[ 4  8 15 16 23 42]
[ 8 15 16 23 42]
[15 16 23 42]
[16 23 42]


In [43]:
#Everything before an index
array[:4]

array([ 4,  8, 15, 16])

In [45]:
#Inbetween indices
array[2:5]

array([15, 16, 23])

In [46]:
#Negative indices
array[2:-2]

array([15, 16])

In [47]:
#Negative indices
array[:-1]

array([ 4,  8, 15, 16, 23])

In [49]:
#Reserve an array
reserve_arr = array[::-1]
reserve_arr

array([42, 23, 16, 15,  8,  4])

In [50]:
reserve_array = np.flip(array)
reserve_array

array([42, 23, 16, 15,  8,  4])

#### Sorting vectors

In [53]:
array = np.array([3,15, 4, 8, 15, 23, 4, 42])
# arr.sort() is a method for in place sorting
array.sort()
print(array)

[ 3  4  4  8 15 15 23 42]


In [57]:
%%time
array = np.array([3,15, 4, 8, 15, 23, 4, 42])
# np.sort() is a function returning a sorted array
sorted_array = np.sort(array)
print(f'sorted_array= {sorted_array}')
print(f'original_array = {array}')

sorted_array= [ 3  4  4  8 15 15 23 42]
original_array = [ 3 15  4  8 15 23  4 42]
CPU times: total: 0 ns
Wall time: 0 ns


#### Copies and Views

In [59]:
#Reserve an array
array = np.array([3,15, 4, 8, 15, 23, 4, 42])
reserve_arr = array[::-1]

reserve_arr
reserve_arr[0] = 1000
print(f'modified: {reserve_arr}')
print(f'original: {array}') #IT HAS ALSO CHANGE

#Slicing created a 'views'

modified: [1000    4   23   15    8    4   15    3]
original: [   3   15    4    8   15   23    4 1000]


In [69]:
#Make array positive 
array = np.array([-4, 8, 15, 16, 23, 42])
positive_array = np.abs(array)
print(positive_array)

positive_array[0] = 1000
print(f'modified: {positive_array}')
print(f'original: {array}')
#It has not changed
#np.abs() created a 'copy'

[ 4  8 15 16 23 42]
modified: [1000    8   15   16   23   42]
original: [-4  8 15 16 23 42]


#### Aggregate functions

In [2]:
import numpy as np
array = np.array([4, 8, 15, 16, 23, 42])
#print(dir(array))

sum_of_arr = 0
for num in array:
    sum_of_arr += num
print(f'Sum of array: {sum_of_arr}')

# Find sum
sum_of_array = np.sum(array)
print(f'sum of arr: {sum_of_array}')

# Mean
mean_of_array = np.mean(array)
print(f'mean of array: {mean_of_array}')

# Product
prod_of_array = np.prod(array)
print(f'prod of array: {prod_of_array}')

Sum of array: 108
sum of arr: 108
mean of array: 18.0
prod of array: 7418880


In [3]:
#Max/Min
print(f'max: {np.max(array)}')
print(f'min: {np.min(array)}')

#Argmax/Argmin

print(f'argmax: {np.argmax(array)}')
print(f'argmin: {np.argmin(array)}')


max: 42
min: 4
argmax: 5
argmin: 0
